# Site settings
title: Rabi Shankar's Resume
nickname: mullu
description: >- # this means to ignore newlines until "baseurl:"
  Hello, I am Rabi Shankar and this is my Online Resume
baseurl: "/resume"  # the subpath of your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: '' 


# Build settings
markdown: kramdown


# Author Info
author:
  name     : Rabi Shankar
  website  : https://aboutrabi.weebly.com/
  email    : shankar.rabi24@gmail.com
  github   : rabi-shankar
  twitter  : rabishankar24
  linkedin : rabishankar-mandi-89081a117
  facebook : rabi.shankar.77

# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
